import desImg1 from '../../images/Image/CoxsBazar.jpg';
import desImg2 from '../../images/Image/Sajek.png';
import desImg3 from '../../images/Image/Sreemongol.png';
import desImg4 from '../../images/Image/sundorbon.png';
import hotelImg1 from '../../images/Image/Rectangle 26.png';
import hotelImg2 from '../../images/Image/Rectangle 27.png';
import hotelImg3 from '../../images/Image/Rectangle 28.png';

const DestinationData = [
    {
        id: "1",
        title: "Cox's Bazar",
        shortDes: "Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach, and it ...",
        longDes: "Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues and centuries-old Buddhist manuscripts. South of town, the tropical rainforest of Himchari National Park has waterfalls and many birds. North, sea turtles breed on nearby Sonadia Island.",
        img: `${desImg1}`,
        mapSrc:"https://www.google.com/maps/embed?pb=!1m12!1m8!1m3!1d59424.35698571978!2d91.96313!3d21.428368!3m2!1i1024!2i768!4f13.1!2m1!1scox&#39;s%20bazar%20hotels!5e0!3m2!1sen!2sbd!4v1600336674406!5m2!1sen!2sbd" ,

        hotel: [
            {
                hotelImg: `${hotelImg1}`,
                hotelId: "1",
                hotelTitle: "Light bright airy apt & safe peaceful stay",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.9",
                starByPerson: "20",
                price: "$34",
                total: "$162",

            },
            {
                hotelId: "2",
                hotelImg: `${hotelImg2}`,
                hotelTitle: "Apartment in Lost Paradise",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.8",
                starByPerson: "10",
                price: "$52",
                total: "$167",
            },
            {
                hotelId: "3",
                hotelImg: `${hotelImg3}`,
                hotelTitle: "AR Lounge (r&r + b&b)",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibilitty available",
                star: "4.9",
                starByPerson: "25",
                price: "$44",
                total: "$162",
            },   
        ],
    },
    {
        id: "2",
        title: "Sajek" ,
        shortDes: "",
        longDes: "Sajek is located in the verdant hills of Kasalong range of mountains amidst the serene and exotic beauty of nature. You will notice lofty mountains, dense forest, sprawling grasslands and miles and miles of hilly tracks. On the way you will cross Mayni range, River Mayni and River Kasalong where you will feel that the green and blue harmonized together.",
        img: `${desImg2}`,
        mapSrc: "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d14648.747604925467!2d92.2861861661455!3d23.38145495632303!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sSajek%20hotels!5e0!3m2!1sen!2sbd!4v1600334519521!5m2!1sen!2sbd",
        hotel:[
            {
                hotelImg: `${hotelImg1}`,
                hotelId: "1",
                hotelTitle: "Light bright airy apt & safe peaceful stay",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.9",
                starByPerson: "20",
                price: "$34",
                total: "$162",

            },
            {
                hotelId: "2",
                hotelImg: `${hotelImg3}`,
                hotelTitle: "Apartment in Lost Paradise",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.8",
                starByPerson: "10",
                price: "$52",
                total: "$167",
            },
            {
                hotelId: "3",
                hotelImg: `${hotelImg2}`,
                hotelTitle: "AR Lounge (r&r + b&b)",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibilitty available",
                star: "4.9",
                starByPerson: "25",
                price: "$44",
                total: "$162",
            },   
        ],
    },
    {
        id:"3",
        title: "Sreemangal" ,
        shortDes: "",
        longDes: "Sreemangal is a hilly area covered with tea estates. There are 47 tea gardens in Sreemangal. A large portion of world’s highest quality tea is grown here. It is also called the city of ‘two leaves and a bud. Sreemangal is famous for nature,forests and wildlife.",
        img: `${desImg3}`,
        mapSrc:"https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d232559.67978963695!2d91.59602266116495!3d24.390172802402798!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sSreemangal%20hotels!5e0!3m2!1sen!2sbd!4v1600334598474!5m2!1sen!2sbd",
        hotel:[
            {
                hotelImg: `${hotelImg2}`,
                hotelId: "1",
                hotelTitle: "Light bright airy apt & safe peaceful stay",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.9",
                starByPerson: "20",
                price: "$34",
                total: "$162",

            },
            {
                hotelId: "2",
                hotelImg: `${hotelImg3}`,
                hotelTitle: "AR Lounge (r&r + b&b) ",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.8",
                starByPerson: "10",
                price: "$52",
                total: "$167",
            },
            {
                hotelId: "3",
                hotelImg: `${hotelImg1}`,
                hotelTitle: "Apartment in Lost Paradise",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibilitty available",
                star: "4.9",
                starByPerson: "25",
                price: "$44",
                total: "$162",
            },   
        ],
    },
    {
        id: "4",
        title: "Sundarbans" ,
        shortDes: "",
        longDes: "The Sundarbans Ecosystem contains diverse flora and fauna is about 10,000 Sq. km of which roughly 60% lies in the south-west of Bangladesh is the world’s largest 35 species true tidal mangrove forest adapted aerial roots breath taking for respiration where living faunal diversity plays an important role in mangrove ecosystem. The Sundarbans is the magnificent rich wildlife conservation including Royal Bengal Tiger habitation area of local and global valued.",
        img: `${desImg4}`,
        mapSrc:"https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d472673.6416297548!2d88.86250024192324!3d22.24907588200587!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sSundarbans%20hotels!5e0!3m2!1sen!2sbd!4v1600334690184!5m2!1sen!2sbd",        hotel:[
            {
                hotelImg: `${hotelImg3}`,
                hotelId: "1",
                hotelTitle: "AR Lounge (r&r + b&b) ",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.9",
                starByPerson: "20",
                price: "$34",
                total: "$162",

            },
            {
                hotelId: "2",
                hotelImg: `${hotelImg1}`,
                hotelTitle: "Light bright airy apt & safe peaceful stay",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibility available",
                star: "4.8",
                starByPerson: "10",
                price: "$52",
                total: "$167",
            },
            {
                hotelId: "3",
                hotelImg: `${hotelImg2}`,
                hotelTitle: "Apartment in Lost Paradise",
                guests: "4",
                bedrooms: "2",
                beds: "2",
                baths: "2",
                features: "Wifi Air-conditioning Kitchen",
                cancel: "Cancellation Flexibilitty available",
                star: "4.9",
                starByPerson: "25",
                price: "$44",
                total: "$162",
            },   
        ],
    }
];
export default DestinationData;